id: A0709F670
title: Prayer to Khandro Tsering Chödrön
type: translation
pechas:
- I51756FA8
- I2F3A9954
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:34.112867
  last_modified_at: 2023-01-04 12:48:34.112873
  collections:
  - Khandro Tsering Chödrön Series
  - Works of Tibetan Masters
alignment_to_base:
  I51756FA8/48DD: '7497'
  I2F3A9954/F7C7: '7497'
